### ISSUE TITLE
Incorrect indentation for DATA_PATH

### ISSUE THREAD

**Issue by riklempens** [infrasonar/appliance-installer#1]
Incorrect indentation in the generated docker-compose.yml file for `DATA_PATH` in the `rapp` section

```yaml
## InfraSonar docker-compose.yml file
##
## !! This file is managed by InfraSonar !!

services:
  agentcore:
    environment:
      AGENTCORE_ZONE: ${AGENTCORE_ZONE_ID}
      HUB_HOST: hub.infrasonar.com
      LOG_COLORIZED: 1
      LOG_LEVEL: info
      TOKEN: ${AGENTCORE_TOKEN}
    image: ghcr.io/infrasonar/agentcore
    labels: &id001
      com.centurylinklabs.watchtower.scope: ${AGENTCORE_TOKEN}
    logging: &id002
      options:
        max-size: 5m
    network_mode: host
    restart: always
    volumes: &id003
    - ./data:/data/
  rapp:
    environment:
      COMPOSE_FILE: /etc/infrasonar/docker-compose.yml
      CONFIG_FILE: /etc/infrasonar/data/config/infrasonar.yaml
      ENV_FILE: /etc/infrasonar/.env
	  DATA_PATH: ./data
      USE_DEVELOPMENT: 0
    image: ghcr.io/infrasonar/rapp
    labels: *id001
    logging: *id002
    network_mode: host
    restart: always
    volumes:
    - /etc/infrasonar:/etc/infrasonar
    - /var/run/docker.sock:/var/run/docker.sock
  watchtower:
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_INCLUDE_RESTARTING: true
      WATCHTOWER_POLL_INTERVAL: 21600
      WATCHTOWER_SCOPE: ${AGENTCORE_TOKEN}
    image: containrrr/watchtower
    labels: *id001
    logging: *id002
    network_mode: host
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /etc/localtime:/etc/localtime:ro
x-infrasonar-template:
  labels: *id001
  logging: *id002
  network_mode: host
  restart: always
  volumes: *id003
```

_Reported via email_
